### ISSUE TITLE
Create plugin hooks in the processing pipeline

### ISSUE THREAD

**Issue by benduran** [benduran/simplestyle#6]
### Acceptance Criteria
- [x] Create pre-process, post-process and optional mid-process hooks
- [x] Allow engineers to return styles in each step to be further processed later down the stream, similar to Next / Connect / Express-style middleware

**Comment by johannes-z** [comment]
@benduran What's the progress on this? This feature is very important for vendor prefixing.

**Comment by benduran** [comment]
@johannes-z thanks for the ping! I have a stale Branch out with some preliminary work done that needs to be revisited.

Do you have an ETA on when you'd need to feature so that I can prioritize accordingly?

**Comment by benduran** [comment]
@johannes-z PR is out. Still needs some additional tests added to it, and a few extra bells and whistles (and documentation), but the feature is largely there. Thanks for your patience!

**Comment by benduran** [comment]
@johannes-z this feature has been released, which I think warrants `simplestyle-js` to be pushed to version `1.0.0`! I'd love for you to give it a try, if you have time. There are some examples in the readme, and you can checkout https://github.com/benduran/simplestyle/blob/master/test/pluginHooks.test.ts for more examples
